spring:
  profiles:
    active: dev
    include: secret
  security:
    oauth2:
      client:
        registration:
          kakao:
            scope:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:5173/oauth/callback/kakao'
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: joeun065@gmail.com
    password: NEED_TO_INPUT_ON_SECRET
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
myapp:
  image-path: file:/Users/dev/Desktop/java/helloCar/frontapp/static/img/
#  file:/Users/kimjoeun/java/중플2/hellocar/frontapp/static/img/ 조은
#  file:/Users/dev/Desktop/java/helloCar/frontapp/static/img/ 경현

